# -*- coding: utf-8 -*-
"""Flood histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPpyAEVRuNswKBv_cu3ISQqF0tkXkpdA
"""

!pip install --upgrade --pre xee
!pip install -U geemap

import ee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

import geemap


roi = ee.Geometry.Rectangle([
    79.85, 6.45,   # xmin, ymin
    80.25, 6.85    # xmax, ymax
])

def ndwi(img):
  qa_band = img.select('QA_PIXEL')
  bit1 = qa_band.bitwiseAnd(1 << 1).neq(0)
  bit2 = qa_band.bitwiseAnd(1 << 2).neq(0)
  bit3 = qa_band.bitwiseAnd(1 << 3).neq(0)
  bit4 = qa_band.bitwiseAnd(1 << 4).neq(0)
  mask = bit1.Or(bit2).Or(bit3).Or(bit4)
  sr = img.select('SR.*').multiply(2.75e-05).add(-0.2)
  index = sr.normalizedDifference(['SR_B3','SR_B5']).rename('ndwi')
  return index.updateMask(mask.Not()).copyProperties(img,['system:time_start'])

def ndwi(img):

    qa = img.select('QA_PIXEL')

    # QA bits
    dilated = qa.bitwiseAnd(1 << 1).neq(0)
    cirrus  = qa.bitwiseAnd(1 << 2).neq(0)
    cloud   = qa.bitwiseAnd(1 << 3).neq(0)
    shadow  = qa.bitwiseAnd(1 << 4).neq(0)

    # Combined cloud mask
    mask = dilated.Or(cirrus).Or(cloud).Or(shadow)

    # Surface Reflectance Scaling
    sr = (
        img.select('SR_B.*')
        .multiply(2.75e-05)
        .add(-0.2)
    )

    # NDWI
    ndwi = sr.normalizedDifference(
        ['SR_B3', 'SR_B5']
    ).rename('ndwi')

    return (
        ndwi
        .updateMask(mask.Not())
        .copyProperties(
            img,
            ['system:time_start']
        )
    )

landsat = (
    ee.ImageCollection(
        "LANDSAT/LC08/C02/T1_L2"
    )
    .filterDate(
        '2016-06-12',
        '2017-06-30'
    )
    .filterBounds(roi)
    .filter(
        ee.Filter.lt(
            'CLOUD_COVER',
            20
        )
    )
    .map(ndwi)
)

print(
    'Collection Size:',
    landsat.size().getInfo()
)

from shapely.geometry import shape

roi_shape = shape(roi.getInfo())
roi_shape

from xee import helpers

landsat.first().select('SR_B4').projection()

grid_params = helpers.fit_geometry(
    geometry=roi_shape,
    grid_crs='EPSG:32644',
    grid_scale=(100, -100)
)

import xarray as xr

ds = xr.open_dataset(
    landsat_ndwi,
    engine ='ee',
    **grid_params
)

ds = ds.sortby('time') * 1

baseline = (
    ds.sel(
        time=slice(
            '2017-03-01',
            '2017-03-30'
        )
    )
    .median(
        dim='time',
        skipna=True
    )
)

flood = (
    ds.sel(
        time=slice(
            '2017-04-01',
            '2017-05-30'
        )
    )
    .max(
        dim='time',
        skipna=True
    )
)

import numpy as np


baseline_vals = (
    baseline.ndwi.values
    .flatten()
)

baseline_vals = baseline_vals[
    np.isfinite(baseline_vals)
]

flood_vals = (
    flood.ndwi.values
    .flatten()
)

flood_vals = flood_vals[
    np.isfinite(flood_vals)
]

plt.figure(figsize=(7,6))

baseline.ndwi.plot(
    x='x',
    y='y',
    robust=True,
    cmap='Blues'
)

plt.title(
    'Pre-Flood NDWI'
)

# Rotate x-axis labels
plt.xticks(rotation=45)

# Reduce tick density
plt.locator_params(axis='x', nbins=5)

plt.tight_layout()

plt.show()

plt.figure(figsize=(7,6))

flood.ndwi.plot(
    x='x',
    y='y',
    robust=True,
    cmap='Blues'
)
plt.title(
    'Flood NDWI'
)

# Rotate x-axis labels
plt.xticks(rotation=45)

# Reduce tick density
plt.locator_params(axis='x', nbins=5)

plt.tight_layout()

plt.show()

plt.figure(figsize=(7,5))

plt.hist(
    baseline_vals,
    bins=200,
    alpha=0.5,
    label='Pre-Flood',
    color='tab:red'
)

plt.hist(
    flood_vals,
    bins=200,
    alpha=0.5,
    label='Flood',
    color='tab:blue'
)

plt.legend()

plt.xlabel('NDWI')

plt.ylabel('Pixel Count')

plt.title(
    'NDWI Histogram Comparison'
)

plt.grid(
    linestyle=':'
)

plt.show()

fig, ax = plt.subplots(
    1, 3,
    figsize=(14,4)
)

# -------------------------------
# Pre-Flood
# -------------------------------

baseline.ndwi.plot(
    x='x',
    y='y',
    robust=True,
    cmap='Blues',
    ax=ax[0],
    cbar_kwargs={
        'orientation':'horizontal',
        'pad':0.05,
        'label':'Pre-Flood NDWI'
    }
)

ax[0].set_title(
    'Pre-Flood'
)

ax[0].tick_params(
    left=False,
    bottom=False,
    labelleft=False,
    labelbottom=False
)

ax[0].set_xlabel('')
ax[0].set_ylabel('')

# -------------------------------
# Histogram
# -------------------------------

ax[1].hist(
    baseline_vals,
    bins=200,
    color='tab:red',
    alpha=0.5,
    label='Pre-Flood'
)

ax[1].hist(
    flood_vals,
    bins=200,
    color='tab:blue',
    alpha=0.5,
    label='Flood'
)

ax[1].legend()

ax[1].set_title(
    'Histogram Comparison'
)

ax[1].set_xlabel('NDWI')

ax[1].set_ylabel('Pixel Count')

# -------------------------------
# Flood
# -------------------------------

flood.ndwi.plot(
    x='x',
    y='y',
    robust=True,
    cmap='Blues',
    ax=ax[2],
    cbar_kwargs={
        'orientation':'horizontal',
        'pad':0.05,
        'label':'Flood NDWI'
    }
)

ax[2].set_title(
    'Flood'
)

ax[2].tick_params(
    left=False,
    bottom=False,
    labelleft=False,
    labelbottom=False
)

ax[2].set_xlabel('')
ax[2].set_ylabel('')

plt.tight_layout()

plt.savefig(
    'flood_histogram_analysis.png',
    dpi=360,
    bbox_inches='tight'
)

plt.show()

baseline.ndwi.plot(x = 'x', y ='y', robust = True)

import matplotlib.pyplot as plt

baseline.ndwi.values.flatten()

plt.hist(baseline.ndwi.values.flatten(), bins = 200)
plt.show()

print(ds.time.values)

flood = ds.sel(time = '2017-08-09', method = 'nearest')

flood.ndwi.plot(x = 'x', y = 'y', robust = True)

plt.hist(flood.ndwi.values.flatten(), bins = 200)
plt.show()

fig, ax = plt.subplots(1, 3, figsize = (13,4))

baseline.ndwi.plot(x = 'x', y = 'y', robust = True, ax = ax[0],
                   cbar_kwargs = {'orientation':'horizontal', 'pad': 0.05,
                                  'label':'pre-flood'})

ax[0].tick_params(left = False, bottom = False, labelleft = False, labelbottom = False)
ax[0].set_ylabel('')
ax[0].set_xlabel('')

flood.ndwi.plot(x = 'x', y ='y', robust = True, ax = ax[2],
                cbar_kwargs = {'orientation': 'horizontal', 'pad': 0.05,
                               'label':'post-flood'})

ax[2].tick_params(left = False, labelleft = False, bottom = False, labelbottom = False)
ax[2].set_ylabel('')
ax[2].set_xlabel('')

ax[1].hist(flood.ndwi.values.flatten(), bins = 200, color = 'tab:blue', label = 'post-flood', alpha = 0.5)
ax[1].hist(baseline.ndwi.values.flatten(), bins = 200, color = 'tab:red', label = 'pre-flood', alpha = 0.5)
ax[1].legend()

plt.savefig('flood_hist.png', dpi = 360, bbox_inches ='tight')
plt.show()